enum errors_t {
	NO_CONF_FILE_FOUND = 1,
	NO_PROFILE_FOUND,
	NO_AVAILABLE_CRTC,
	NO_ARGUMENT_GIVEN,
	INSUFFICIENT_MEMORY,
	DUPLICATE_OUTPUT,
	DAEMON_ALREADY_RUNNING,
	NO_HOME_DIR,
	MULTIPLE_ACTION,
	CANNOT_CREATE_LOCK
};
